FROM amazonlinux:latest

RUN yum install -y wget bzip2 libXrender libXext

RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && bash `ls *-x86_64.sh` -b

ENV PATH /root/miniconda3/bin:$PATH

# See http://www.rdkit.org/docs/Install.html#how-to-install-rdkit-with-conda
RUN conda install -c rdkit -y python==3.6 rdkit

# Add application components
RUN conda install flask scikit-learn numpy psycopg2

ENV RDBASE=/rdkit

RUN mkdir $RDBASE

COPY app $RDBASE/app
WORKDIR $RDBASE
